Opening 1xka.pdb...
Opening model7.pdb...
model7.pdb opened
Traceback (most recent call last):
  File "/home/malgorzata/chimera/share/chimeraInit.py", line 761, in init
    midas_text.doRunScript("runscript", script)
  File "/home/malgorzata/chimera/share/Midas/midas_text.py", line 2251, in doRunScript
    execfile(scriptPath, scriptGlobals)
  File "18_RMSD.py", line 13, in <module>
    rc("matchmaker #0 #1 ")
  File "/home/malgorzata/chimera/share/chimera/__init__.py", line 2791, in runCommand
    makeCommand(*args, **kw)
  File "/home/malgorzata/chimera/share/Midas/midas_text.py", line 69, in makeCommand
    f(c, args)
  File "/home/malgorzata/chimera/share/MatchMaker/ChimeraExtension.py", line 43, in cmdMatchMaker
    ("matchSpec", "matchSel", None)])
  File "/home/malgorzata/chimera/share/Midas/midas_text.py", line 451, in doExtensionFunc
    extFunc(*tuple(processedArgs), **kw)
  File "/home/malgorzata/chimera/share/MatchMaker/__init__.py", line 554, in cmdMatch
    raise MidasError("No reference model specified")
MidasError: No reference model specified

